language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: hFOn0BoGBvCA8oOtueRPsmII2ME0lt82daIR1+h9QOhEz0rbRCRPu4iZqTCMM7JQBQedN3q1XVC8SlJMKT+Q9SBC5Zxqf6ZjGtGBXM3h4TQDGK0VkPcqbjgYfNAEonz09WLQz24eUey4ymX7SImvB50AUwor8RZNi5tQCit0a9KBIwGuz0haTMLRdMoY9rcEvbm2/09pj6dOlKXSTirOUH7mEH42nlZtIMKD6Y2HR1TTPK65yEt76cY9jHf4Qy15vAyDKA/noU+nvR+ekwMPUwGVMt6yvMKO7MzhULwLFB2pqgw7bjAUZzgPqXSgWbIhHXXa5VV3D3dRjFR90YnrsThMFYgPz5jjXfsR/Y9SvczigtHnqQmhLIFwqNbEJy6+K9bSU+Ur6EYopAAQX90DMTjkWKQBirSzON09EAfHCY+t1hCI8Ldh2SjuOFqhCq5DruD00+oabKYazRMENIGrp9QiFYGYByKbG9TBuWlpm21P1TwSWqhOsCUcchWxsu7bERnGFCt2BH7Y7YPN1zSzmMQ562Ebt6dFAYsh3udslT8K8ctkM0G2OKEWILdfLUiZI1OPZsA2TB6RdMSVjlfsYAJwFSSShbWdAD/S+39u1vaqDmc7diByHunjzlgFm1u1VqsTkh0udTxGUY/MClZN0vasVhO5XKznb1e+7EJv+k0=
  - secure: wL93HpaS7PkBQ/Xlt5yS2DT7EJZIVW/dBY4Kd+AYHSV5ra85fRiO/oZYZLv98IRdgX+3ZpoTzBOe49RprP0L+2jRL9690IMgUL/PZKI0Ejbj3UXvGw+197gAR7ghdSenoFHOz4zkhFyDKymrA096GCUzLG0mfyp8aeDORMw1efKJ2WO/qUSSRx/4Jm/SUNEmGqWYpwkq9UddczCwkxFvu9mz+tZmKhUsWuh4aGB5eTqfLPg1+izO5J2BcSP9bZD3BdkvJcFp9fRm17LjSLrV906y6J5FT9iXxpF5DkHzPPzdU2nQHacDCy2PkHtHM+2QVdyiwId06pcWGwdOjay0ZZImwuYqSAALYdanOAKCHaNLGvulvWPsyRliY5WfUUwGTChm3dXmJfsjlRlEZnqpNROKs9ZgSDhqNx9qOOtMbX0FzSFvZHl9xhm9cyGIxYAEXfaxU6UUS7jdDzSpb9JwnXt4vhiQu2jrkH51UUYJBYARpyOT0tJkFVUKGr5UeNtLq7AAKde584UrIMyj1I4cSVt+2/EnO45yarRfVSvqA980AM5U46F3f2MXK01rNO786vwo4SxylINUDl0rbodqsI45AgNA/sc5fPpMc+CrZLFl0lMaKmqaoesYr4pdYSTmRzSXz1CYE8JCHfxQ8MfoaVdtPl5ADVcCDLLVr99yQf4=
